<template>
  <div>
    <h1 class="text-center text-3xl text-gray-500">Data Table</h1>

    <div class="container bg-white mx-auto p-5">
      <DataTable :columns="columns" :entries="entries" :isColId="true" />
    </div>
  </div>
</template>

<script>
import DataTable from "../components/table/DataTable.vue";
export default {
  name: "components",
  components: { DataTable },
  data() {
    return {
      columns: [
        { name: "id", text: "ID" },
        { name: "name", text: "Nome" },
        { name: "office", text: "Profissão" },
        { name: "startData", text: "Data de Inicio" },
        { name: "salary", text: "Salário" },
      ],
      entries: [
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
        {
          id: 1,
          name: "Wesley",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 2,
          name: "Arthur Nunes",
          office: "Manager",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 3,
          name: "Maria Clara",
          office: "Administradora",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 4,
          name: "Pollyanna",
          office: "Designer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 5,
          name: "Arthur",
          office: "Developer",
          startData: "2022-01-30",
          salary: 23547,
        },
        {
          id: 6,
          name: "Heitor",
          office: "CEO",
          startData: "2022-01-30",
          salary: 23647,
        },
      ],
    };
  },
};
</script>


<style>
</style>